SELECT o.PRODUCT_ID, p.PRODUCT_NAME, sum(p.PRICE*o.AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER as o JOIN FOOD_PRODUCT AS p
ON o.PRODUCT_ID = p.PRODUCT_ID
WHERE MONTH(o.PRODUCE_DATE) = 5 AND YEAR(o.PRODUCE_DATE) = 2022
GROUP BY o.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, o.PRODUCT_ID
